project:
  type: website
  output-dir: _site
website:
  title: "The 2nd Trial"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Articles
        href: articles.qmd
theme:
  - custom.scss
